env:
  global:
    - secure: "QL962wkIoJCUArk44n2jsp9k7SNmqu4179U7fv8iV3knKmV6atiQVjoLkqgtTTLsIA/9O5IY7KJneaMU6GUKwWcGTfSEgWS7MIR1GUSzXCBwBgOEG5fmTNZ6GsueQj/n00VQBEKFktT7DG8eAzLpy27avFKGavTQU1x79LWUYOo="

matrix:
  include:
    - os: osx
      env: TORC=osx
      compiler: clang
      before_install:
        - |
          if [[ $TRAVIS_BRANCH != "coverity_scan" ]]; then
            brew install qt5
            brew link qt5 --force
          else
            echo Ignoring branch
          fi

      script:
        - |
          if [[ $TRAVIS_BRANCH != "coverity_scan" ]]; then
            qmake torc.pro
            make
          else
            echo Ignoring branch
          fi

    - os: linux
      env: TORC=linux
      dist: xenial
      compiler: gcc
      before_install:
        - |
          if [[ $TRAVIS_BRANCH != "coverity_scan" ]]; then
            sudo apt-get update
            sudo apt-get install libgraphviz-dev libavahi-compat-libdnssd-dev qt5-default libxml2-dev
          fi

      script:
        - |
          if [[ $TRAVIS_BRANCH != "coverity_scan" ]]; then
            qmake torc.pro
            make
          else
            echo Ignoring branch
          fi

    - os: linux
      env: TORC=coverity_scan
      dist: xenial
      compiler: gcc
      before_install:
        - |
          if [[ $TRAVIS_BRANCH == "coverity_scan" ]]; then
            sudo apt-get update
            sudo apt-get install libgraphviz-dev libavahi-compat-libdnssd-dev qt5-default libxml2-dev
          fi

        - echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-

      addons:
        coverity_scan:
          project:
            name: "mark-kendall/torc"
            description: "Torc"
          notification_email: mark.kendall@gmail.com
          build_command_prepend: "qmake torc.pro"
          build_command: "make"
          branch_pattern: coverity_scan

language: cpp
