env:
  global:
    - secure: "JcGGQSB6S5999makDLfl8W7+8YhMo9pj55VhOx+xGBe5dfUjJH9u8d2M7sFz1aNeV2ntdqgtUl4SCip/4MgyHIKHjRwY/Bb087oy4AECxBA3+7IVXx5leR+M9iPvFk5LAmArQujvmZwhe07L1RuZEgCIypQOJ3n6R/NCUUYZ2nc="

matrix:
  include:
    - os: osx
      env: TORC=osx
      compiler: clang
      before_install:
        - brew install qt5
        - brew link qt5 --force
    - os: linux
      env: TORC=linux
      dist: xenial
      compiler: gcc
      before_install:
        - sudo apt-get update
        - sudo apt-get install libgraphviz-dev libavahi-compat-libdnssd-dev qt5-default libxml2-dev
    - os: linux
      env: TORC=coverity_scan
      dist: xenial
      compiler: gcc
      before_install:
        - |
          if [[ "$TORC" == "coverity_scan" ]]; then
            sudo apt-get update
            sudo apt-get install libgraphviz-dev libavahi-compat-libdnssd-dev qt5-default libxml2-dev
            echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-
          fi

      script:
        - echo Done
      addons:
        coverity_scan:
          project:
            name: "mark-kendall/torc"
            description: "Torc"
          notification_email: mark.kendall@gmail.com
          build_command_prepend: "qmake torc.pro"
          build_command: "make"
          branch_pattern: coverity_scan

language: cpp

script:
  - qmake torc.pro
  - make
