matrix:
  include:
    - os: linux
      dist: xenial
    - os: osx

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get update ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install libgraphviz-dev libavahi-compat-libdnssd-dev qt5-default libxml2-dev ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install qt5 ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then echo 'export PATH="/usr/local/opt/qt/bin:$PATH"' >> ~/.bash_profile; fi

language: cpp

script:
        - qmake torc.pro
        - make
