matrix:
  include:
    - os: linux
      dist: xenial
    - os: osx

addons:
  apt:
    packages:
      - libgraphviz-dev
      - libavahi-compat-libdnssd-dev
      - qt5-default
      - libqt5xmlpatterns5-dev
      - libxml2-dev

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install qt5          ; fi

language: cpp

script:
        - qmake torc.pro
        - make
