matrix:
  include:
    - os: osx
    - os: linux
      dist: xenial

compiler:
  - gcc
  - clang

before_install:
  - |
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      sudo apt-get update
      sudo apt-get install libgraphviz-dev libavahi-compat-libdnssd-dev qt5-default libxml2-dev
    fi
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      brew install qt5
      brew link qt5 --force
    fi

language: cpp

script:
  - qmake torc.pro
  - make
