env:
  global:
   - secure: "o/zpwMgNrWsEK7NoH9gByY2UGZKyzJyZDhD3OQtKruS3ZXsXo411JC4KE8ZMnSPPuoSR1FSbsldrwnNwiRhlGkbZ9uDCt8mUree20bDzW/hYnYwKyq1NTrbSd5m0WcFGh2uk9NnkjGdjmgY9HPpXD+cyFp645jOXzJHg5Krk6XWrR9I7jDvO6J/+zr31of4m9Yp0Vnl9JTKGcitbLDbfpezLsgpcOLyR4/lGorL3Y5mXEYxODUqxtnMTQmKYxf0658gRUiERw4j7+Qe/r1PbKTJ0t+tn7kSHJVcV7rwJ70hrwQqiWro05c1DBN22wdN4EfZFRQIyMzOyA34mOk2HXEm5N/4408pYAGKGZpWabBrd/+6xGCGQKTylITiPHo8hjlXR4jGkDJbZZJ+Ij02gxCM6mAEsQlcwT4W6Hl76yMB7Y9SRZTpw6+Txf+I1ip2xrWMLa2eVkcMgE6Z8xllXQ3ulceQPhpyjm4NjcU4B8jLYXaoLva3nzTiGe85HF0PGBonCaFb5tvLpZdHmiHtusorK737YPsP20Cx2J84fO1lsxggIkn34IjRThlfQYoBaDcER128HhI9eLqBX+IWL98HvBgHGHeI8/nCfmSR6fdzHWL6lxOzELQjBvEz6UO+PACs3m3xNW2NwLiup3pAsfv3gc1P/D+2e8DacahJ0SvM="

language: cpp

matrix:
  include:
    - os: linux
      env: TORC=coverity_scan
      dist: xenial
      compiler: gcc
      before_install:
        - |
          if [[ $TRAVIS_BRANCH == "coverity_scan" ]]; then
            travis_retry sudo apt-get update
            travis_retry sudo apt-get install libgraphviz-dev libavahi-compat-libdnssd-dev qt5-default libxml2-dev
          else
            echo Ignoring branch
          fi
          echo -n | openssl s_client -connect https://scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-

      script:
        - echo Done!
      addons:
        coverity_scan:
          project:
            name: "mark-kendall/torc"
            description: "Torc"
          notification_email: mark.kendall@gmail.com
          build_command_prepend: "qmake torc.pro"
          build_command: "make -j4"
          branch_pattern: coverity_scan

    - os: osx
      env: TORC=osx
      compiler: clang
      before_install:
        - |
          if [[ $TRAVIS_BRANCH != "coverity_scan" ]]; then
            travis_retry brew install qt5
            travis_retry brew link qt5 --force
            travis_retry brew install ffmpeg
            travis_retry brew link ffmpeg --force
          else
            echo Ignoring branch
          fi

      script:
        - |
          if [[ $TRAVIS_BRANCH != "coverity_scan" ]]; then
            TORC_FFMPEG=1 qmake torc.pro
            make -j4
          else
            echo Ignoring branch
          fi

    - os: osx
      env: TORC=osx-codecov
      compiler: clang
      before_install:
        - |
          if [[ $TRAVIS_BRANCH != "coverity_scan" ]]; then
            travis_retry brew install qt5
            travis_retry brew link qt5 --force
          else
            echo Ignoring branch
          fi

      script:
        - |
          if [[ $TRAVIS_BRANCH != "coverity_scan" ]]; then
            qmake CONFIG+=test torc.pro
            make -j4
            ./torc-tests -c test/config -s . -t i18n
            bash <(curl -s https://codecov.io/bash)
          else
            echo Ignoring branch
          fi

    - os: linux
      env: TORC=linux
      dist: xenial
      compiler: gcc
      before_install:
        - |
          if [[ $TRAVIS_BRANCH != "coverity_scan" ]]; then
            travis_retry sudo apt-get update
            travis_retry sudo apt-get install libgraphviz-dev libavahi-compat-libdnssd-dev qt5-default libxml2-dev
          else
            echo Ignoring branch
          fi

      script:
        - |
          if [[ $TRAVIS_BRANCH != "coverity_scan" ]]; then
            qmake torc.pro
            make -j4
          else
            echo Ignoring branch
          fi

    - os: linux
      env: TORC=linux-codecov
      dist: xenial
      compiler: gcc
      before_install:
        - |
          if [[ $TRAVIS_BRANCH != "coverity_scan" ]]; then
            travis_retry sudo apt-get update
            travis_retry sudo apt-get install libgraphviz-dev libavahi-compat-libdnssd-dev qt5-default libxml2-dev libqt5sql5-sqlite
          else
            echo Ignoring branch
          fi

      script:
        - |
          if [[ $TRAVIS_BRANCH != "coverity_scan" ]]; then
            qmake CONFIG+=test torc.pro
            make -j4
            ./torc-tests -c test/config -s . -t i18n
            bash <(curl -s https://codecov.io/bash)
          else
            echo Ignoring branch
          fi

    - os: linux
      env: TORC=linux-doxygen
      dist: xenial
      before_install:
        - |
          if [[ $TRAVIS_BRANCH != "coverity_scan" ]]; then
            travis_retry sudo apt-get update
            travis_retry sudo apt-get install graphviz doxygen
          else
            echo Ignoring branch
          fi

      script:
        - |
          if [[ $TRAVIS_BRANCH != "coverity_scan" ]]; then
            cd docs
            doxygen doxygen.cfg
            cd ..
          else
            echo Ignoring branch
          fi

      deploy:
        provider: pages
        skip-cleanup: true
        github-token: $GITHUB_TOKEN
        keep-history: true
        local-dir: docs/html
        on:
          branch: master
