dist: xenial

install:
        - sudo apt-get update
        - sudo apt-get install libgraphviz-dev libavahi-compat-libdnssd-dev qt5-default libqt5xmlpatterns5-dev libxml2-dev

language: cpp

script:
        - qmake torc.pro
        - make
